default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: Yo
  password: zeni1211
  pool: 5

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test
