# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ffc4f4dff081c0c3468b8b12d5cd9518717936032b841f57976e16bb7fa2e67191bdc90e4ddcc8e7e6d0298c0e128bd7413b9adbfb6d924d1e4b49e42a1aa999

test:
  secret_key_base: 1f8cb5ba5c9c5fc403d0c1b4d54f4d2d2a9aacc96aae27d096dc52a901ad1cf90ffdc0a5fb619bce092325a2ef52d77110e612acab6cc3ee4116d736a72376e6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
